### ISSUE TITLE
can no longer save images in latest version

### ISSUE THREAD

**Issue by DetachHead** [BandarHL/BHInstagram#34]
in previous versions you could save both videos and images by tapping and holding. in version 1.0 there's now a download button on videos instead, but there doesn't seem to be any way to download images anymore

**Comment by BandarHL** [comment]
Fixed

**Comment by DetachHead** [comment]
@BandarHL i updated to 1.1 and i still can't tap & hold an image to save it anymore. has this changed to a dedicated button like it did with videos? i don't see such a button on images though

**Comment by BandarHL** [comment]
There is a download button you don't need to hold and download

**Comment by DetachHead** [comment]
i can't seem to find the button. there's nothing in the ... menu either

![image](https://github.com/user-attachments/assets/302e8923-6bf0-4e02-a168-3bc30f3e368d)

**Comment by BandarHL** [comment]
Make sure that you have enabled download videos option

**Comment by DetachHead** [comment]
yeah that option is enabled, and i can see the download button on videos. i just can't see a download button on images
